### ISSUE TITLE
Sorting DICOMObject

### ISSUE THREAD

**Issue by HSGorman** [rexcardan/Evil-DICOM#19]
The current default sorting of all DICOMObjects means my DICOM annotations change order which breaks my DICOM viewer. If the sorting is made optional via a property on the DICOMObject this allows things to continue working as is and resolves the issue I have. I've pulled the code from Github and done the change required. If you want the code I have it here (very simple change).

Thanks HSG

By the way great job on the library.

**Comment by HSGorman** [comment]
Hi Rex,

The DICOM tags are for annotations, the relevant DICOM is:

(0070,0001) Graphic Annotation Sequence SQ 1
-BEGIN ITEM 1
-(0008,1140) Referenced Image Sequence SQ 1
--BEGIN ITEM 1
--(0008,1150) Referenced SOP Class UID UI 1 1.2.840.10008.5.1.4.1.1.7
--(0008,1155) Referenced SOP Instance UID UI 1
1.3.6.1.4.1.25403.114374075226142.10588.20141218045854.3
--(0008,1160) Referenced Frame Number IS 1 1
--END ITEM 1
-(0070,0002) Graphic Layer CS 1 USER ANNOTATIONS -(0070,0008) Text Object
Sequence SQ 1
--BEGIN ITEM 1
--(0070,0003) Bounding Box Annotation Units CS 1 PIXEL
--(0070,0006) Unformatted Text Value ST 1 Monkey
--(0070,0010) Bounding Box Top Left Hand Corner FL 2 121.6823\32.08994
--(0070,0011) Bounding Box Bottom Right Hand Corner FL 2 162.4646\44.94836
--(0070,0012) Bounding Box Text Horizontal Justification CS 1 LEFT
--END ITEM 1
-(0008,1140) Referenced Image Sequence SQ 1
--BEGIN ITEM 1
--(0008,1150) Referenced SOP Class UID UI 1 1.2.840.10008.5.1.4.1.1.7
--(0008,1155) Referenced SOP Instance UID UI 1
1.3.6.1.4.1.25403.114374075226142.10588.20141218045854.3
--(0008,1160) Referenced Frame Number IS 1 1
--END ITEM 1
-(0070,0002) Graphic Layer CS 1 USER ANNOTATIONS -(0070,0008) Text Object
Sequence SQ 1
--BEGIN ITEM 1
--(0070,0003) Bounding Box Annotation Units CS 1 PIXEL
--(0070,0006) Unformatted Text Value ST 1 Monkey
--(0070,0010) Bounding Box Top Left Hand Corner FL 2 121.6823\32.08994
--(0070,0011) Bounding Box Bottom Right Hand Corner FL 2 162.4646\44.94836
--(0070,0012) Bounding Box Text Horizontal Justification CS 1 LEFT
--END ITEM 1
-END ITEM 1

This is for a presentation "PR" and going by the viewer if this section was
sorted by tag the viewer couldn't read it. If I stopped the sorting it
could. Not sure if this is a problem with the viewer, had been assuming it
was correct.

Thanks,

Sam

**Comment by rexcardan** [comment]
I am still not clear on this. What element are you trying to insert? If there is a bug, I will fix it but I can't see the problem. All of those tags are in order.

**Comment by HSGorman** [comment]
Hi Rex,
The area I was in was
 (0008,0016)SOP Class UID

1.2.840.10008.5.1.4.1.1.11.2 so it's a Colour soft copy. The segment is a
0070, 0001 Graphic Annotation Sequence. Followed by 0008,1140 then a
0070,0002 > 0070,0008 Text Object Sequence and 0070,0009. Anyway to cut it
short the viewer is by ClearCanvas and it appears to be particular as to
the sequence of the tags. Having said that it also requires a key object
dcm as well before it shows the annotations. I can send you a copy of the
files if you want and what it looks like in a the viewer.

Sam

**Comment by rexcardan** [comment]
What would help is this:
The original file that works (anonymized of course)
The code you use to insert some element

Then I can look at the order of the tags after insertion and see if they are in the correct order.

**Comment by HSGorman** [comment]
Sorry for the delay things have been a bit crazy....

I've zipped the dcm files together. 23 and 24 are simply images. 29 is the
presentation which is of most interest and 33 is the key object.
In file 29:
0070,0001 are the annotations
0070,0008 is a text object, 0070,0009 is an ellipse etc. The presentation
dcm would only work with the ClearCanvas viewer when order was what it
expected.

 Anyway I've the problem solved using the ClearCanvas library, which saved
me loading an extra DICOM library, but if this is of any help. All the data
is made up and the picture is a lump of meat from the fridge so no data
privacy issues :)

Sam

**Comment by rexcardan** [comment]
I believe the issue is patched now.
