### ISSUE TITLE
Private DICOM Elements?

### ISSUE THREAD

**Issue by phillipgsmith** [rexcardan/Evil-DICOM#21]
Is there a way to read private DICOM elements? I've tried to just specify the tag but this did not work as I thought it would. Thanks.

**Comment by rexcardan** [comment]
Private elements should be read correctly.

**Comment by phillipgsmith** [comment]
Thanks!

On Tue, Feb 10, 2015 at 8:48 AM, rexcardan <notifications@github.com> wrote:

> Private elements should be read correctly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/rexcardan/Evil-DICOM/issues/21#issuecomment-73701203>.
>



-- 
Phillip Smith
phillip@sweaterboy.com
