### ISSUE TITLE
Special Characters in strings

### ISSUE THREAD

**Issue by Ritterbrater** [rexcardan/Evil-DICOM#24]
I have some clinical CT data here and some strings contain ugly special characters (umlaut: öäü). I know, this is very problematic (I already had troubles in the past). E.g. ö has the hex value 0xF6 and will be replaced by a question mark character. Is it possible to change the encoding (or maybe adding a configuration parameter)?

**Comment by rexcardan** [comment]
I will not add a non DICOM compliant decoder option to the library, but you can do it. Why don't use just call afterwards:
var bytes = ASCII.GetBytes(incorrectlyParsedData);
var correctInterp = MyDecoder.ParseBytes(bytes);
