### ISSUE TITLE
Specific Character Set support.

### ISSUE THREAD

**Issue by ghost** [rexcardan/Evil-DICOM#30]
Hi,

Thanks for a great library, since fo-dicom was shut down recently I have tried using Evil-DICOM for my project and thus far it is working great.

My issue is that Evil-DICOM doesn't seem to utilize C.12.1.1.2 Specific Character Set when reading SH, LO, ST, PN, LT or UT data elements, and its causing a bit of a headache since I live in Sweden and most of the data we have uses ISO_IR 100.

Perhaps there is something I missed or is it a planned feature?

**Comment by rexcardan** [comment]
I don't have any use cases myself where I have seen that issue. You can parse strings yourself if you just override the DICOMString class's Read (see link below) method. Maybe we could add an overload to the Read that allows a specific decoding. Can you show me how you would read in a byte[] to the format you want. I could roll it in and maybe add and overload to DICOMObject.Read(byte[] file, ReadSettings ...) or something.

https://github.com/rexcardan/Evil-DICOM/blob/master/EvilDICOM.Core/EvilDICOM.Core/IO/Data/DICOMString.cs

**Comment by anders9ustafsson** [comment]
Rex, you might want to find some guidance from *fo-dicom* for this issue. [Here](https://github.com/cureos/fo-dicom/blob/portable/DICOM/DicomEncoding.cs) is the code to the `DicomEncoding` class which can be used for selecting the relevant character set in *fo-dicom* IO.
