### ISSUE TITLE
Destination array is not long enough to copy all the items in the collection. Check array index and length.

### ISSUE THREAD

**Issue by robintiwari** [rexcardan/Evil-DICOM#34]
I am getting the following error while trying to parse a DICOM file. This is the file with the Transfer Syntax of Explicit Little Endian (EXPLICIT_VR_LITTLE_ENDIAN).

**Destination array is not long enough to copy all the items in the collection. Check array index and length. System.Exception {System.ArgumentException}**

Below is my code:

```
var dicomFile = System.IO.File.ReadAllBytes(file);
var tst = DICOMFileReader.ReadFileMetadata(file);
var dcm = DICOMObject.Read(file);
```

Any Help would be highly appreciated.
Thanks,
Robin

**Comment by rexcardan** [comment]
You don't by change have an anonymized version you can give me do you? I can debug with a copy and find the root of the issue. I prioritize this kind of error highly.
