### ISSUE TITLE
incorrect handling of 'pending' against dcm4che

### ISSUE THREAD

**Issue by jackdr66** [rexcardan/Evil-DICOM#35]
The validation via Status.PENDING isn't working against dcm4che pacs. Pending status checks are eighter 0xFF00 as well as 0xFF01 so next to 65280, also 65281 should be checked.

**Comment by rexcardan** [comment]
Thanks for the info. I am not quite sure I understand. I have been building up the network components as I need them and so they are not polished. Is there a test I can do to demonstrate state failure?
