### ISSUE TITLE
modifying tag values

### ISSUE THREAD

**Issue by crisguycabs** [rexcardan/Evil-DICOM#37]
Mr Cardan, hello!

I would like to modify a specific tag/element, for example the row number -> dcm.AllElements[39]

I know there are the properties .DData (non casted) and DData_ (casted). I know I have to change both of them, but how to do it with DData? 

For example, Im managing dicom files with dcm.AllElements[39] as object{ushort} 

I appreciate the help

Saludos!

**Comment by rexcardan** [comment]
DData is for setting a single value in the element. DData_ is for getting or setting an array of values. Neither one are strongly typed. If you want strong typing, you can use a selector to get the element you want. Then you use the Data or Data_ for the strongly typed data property. For example:

`var dcm = DICOMObject.Read("....your file"); 
var sel = dcm.GetSelector(); 
sel.PatientName.Data = "John^Smith";
sel.ImageOrientationPatient.Data_ = new List<double>(){1,0,0,0,1,0};
`
