### ISSUE TITLE
Dicom Print

### ISSUE THREAD

**Issue by Valdirnm** [rexcardan/Evil-DICOM#39]
I need to create a tool for printing single Dicom Images(Maybe jpg images too).

I Could find this:(Looking at EvilDicom)

```
        Dim Ent As Entity
        Ent.AeTitle = "DRYPIX"
        Ent.Port = 104
        Ent.IpAddress = "192.168.0.180"
```

I have to build my own printer software.
Is that possible using evilDicom?
I also need set film size and Printer Settings (Resolution, Orientation, Film Size)
Anyone could point me to the right direction?

**Comment by rexcardan** [comment]
This library is a DICOM manipulation library. If you are looking to do more with images pixel values and compression support, I suggest a different library.
