### ISSUE TITLE
Representation of PixelSpacing

### ISSUE THREAD

**Issue by Pippin555** [rexcardan/Evil-DICOM#44]
When I look at the item (0028,0030) Pixel Spacing in DicomBrowser I see a value "1\1",
but when I see the result of DICOMObject.GetSelector().PixelSpacing.GetDataOrDefault();
I only get one double value. Is this correct?

from PS 3.3-2011: 
Physical distance in the patient between the center of each pixel, specified by a numeric pair - adjacent row spacing (delimiter) adjacent column spacing in mm. See 10.7.1.1 and 10.7.1.3. Required if the image has been calibrated. May be present otherwise.

**Comment by Pippin555** [comment]
I dove in it somewhat deeper and found that the GetDataOrDefault only yields the first item. 
The collection should be processed to get all the items. It would be nice to have an interface that gives the result as array...

**Comment by rexcardan** [comment]
EvilDICOM has a syntax that is a little unique. You add an underscore to grab data you want where multiple values are possible. PixelSpacing.Data_ should give you a list of the value type.
