### ISSUE TITLE
CodeString doesn't seem to support mulitplicity > 1?

### ISSUE THREAD

**Issue by zaxasheats** [rexcardan/Evil-DICOM#49]
I'm writing DX Image SOP compliant images and testing for validation with DXVt.  It looks like any fields using CodeString with a multiplicity > 1 just drop the remaining items.  I'm using the V2.0.0 release.  Functionally what I"m writing is this:

`ReplaceOrAdd(
     new CodeString 
     { Tag = TagHelper.ImageType, Data_ = new List<string>{"PRIMARY", "ORIGINAL"});`

But when it does the write I only get "PRIMARY".  Other places with higher multiplicity work OK (so far)  But not with code strings.

Am I doing something wrong or is this a bug?  I can see in DataComposer.cs where I could change the routine to use the DataContainer instead but I'm unsure if that's the right solution.  ImageType and PatientOrientation are both good examples of this.

Thanks, Matt

**Comment by zaxasheats** [comment]
Actually it looks like any of the string based VRs would have the same issue.

**Comment by rexcardan** [comment]
I just made a unit test to do check this problem. It doesn't fail. I'm using the most recent Git repo (don't know about v 2.0.0):


```cs
 [TestClass]
    public class CodeStringMultiplicityTests
    {
        [TestMethod]
        public void CanAddMultipleStringsTest()
        {
            var dcm = new DICOMObject();
            dcm.ReplaceOrAdd(DICOMForge.ImageType("Type1", "Type2", "Type3"));

            var expected = 3;
            var data = dcm.GetSelector().ImageType.Data_;
            var actual = data.Count;
            Assert.AreEqual(expected, actual);

            Assert.AreEqual("Type1", data[0]);
            Assert.AreEqual("Type2", data[1]);
            Assert.AreEqual("Type3", data[2]);
        }
    }
```

**Comment by zaxasheats** [comment]
It is fine in memory.  When it gets written to disk it doesn't use the
multiplicity.  It uses the first item only.  Try the same test with a write
and a read in between.

Thanks,  Matt


On Aug 9, 2017 11:18 AM, "Rex Cardan" <notifications@github.com> wrote:

I just made a unit test to do check this problem. It doesn't fail. I'm
using the most recent Git repo (don't know about v 2.0.0):

 [TestClass]
    public class CodeStringMultiplicityTests
    {
        [TestMethod]
        public void CanAddMultipleStringsTest()
        {
            var dcm = new DICOMObject();
            dcm.ReplaceOrAdd(DICOMForge.ImageType("Type1", "Type2", "Type3"));

            var expected = 3;
            var data = dcm.GetSelector().ImageType.Data_;
            var actual = data.Count;
            Assert.AreEqual(expected, actual);

            Assert.AreEqual("Type1", data[0]);
            Assert.AreEqual("Type2", data[1]);
            Assert.AreEqual("Type3", data[2]);
        }
    }

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/rexcardan/Evil-DICOM/issues/49#issuecomment-321287624>,
or mute the thread

**Comment by rexcardan** [comment]
Interesting. I see the problem in the datacomposer class as well. I will patch today and update this thread when complete.

**Comment by zaxasheats** [comment]
Great!

Thanks, Matt

**Comment by rexcardan** [comment]
Well it is a little weird. I see why I made it like that. The DICOM standard is not really clear how those CodeString can have multiple values. But I did see the ImageType VM > 1 so I put it in. Not all string values can have multiple values (eg. LongText, ShortText, UniversalResourceId). Anyway, I did a first pass with it and I think it should work for you. Here is my new test.
```cs
  [TestMethod]
        public void CanAddMultipleStringsTest()
        {
            var dcm = new DICOMObject();
            dcm.ReplaceOrAdd(DICOMForge.ImageType("Type1", "Type2", "Type3"));

            //Memory test
            var expected = 3;
            var data = dcm.GetSelector().ImageType.Data_;
            var actual = data.Count;
            Assert.AreEqual(expected, actual);

            Assert.AreEqual("Type1", data[0]);
            Assert.AreEqual("Type2", data[1]);
            Assert.AreEqual("Type3", data[2]);


            var bytes = new byte[0];
            //Test IO
            using (var ms = new MemoryStream())
            {
                //WRITE
                using (var bw = new DICOMBinaryWriter(ms))
                {
                    DICOMObjectWriter.Write(bw, DICOMWriteSettings.Default(), dcm);
                }
                bytes = ms.ToArray();
            }

            //READ
            var dcmRead = DICOMObject.Read(bytes);
            expected = 3;
            data = dcmRead.GetSelector().ImageType.Data_;
            actual = data.Count;
            Assert.AreEqual(expected, actual);

            Assert.AreEqual("Type1", data[0]);
            Assert.AreEqual("Type2", data[1]);
            Assert.AreEqual("Type3", data[2]);

        }
```
