### ISSUE TITLE
"Destination array is not long enough to copy all the items in the collection  " Error when reading DICOMDIR file

### ISSUE THREAD

**Issue by pk198105** [rexcardan/Evil-DICOM#57]
Hello 

Using version 2.0.2.8

I'm attempting to read a 2.2MB DICOMDIR file using the following:
[Evildicom.core.Dicomobject]::Read('E:\dicomdir') 

I get the following error:
Exception calling "Read" with "1" argument(s): "Destination array is not long enough to copy all the items in the collection. Check array index and length."

Now from what I can see in the DICOMDIR file, it seems to contain multiple reports with VR = UT of varying lengths.

I will try to provide you with an anonymized version of the said file.

Is it something you believe can be addressed ? I tried reading the file with another DICOM library and it is able to do so but I prefer EvilDICOM much more for my current project

**Comment by rexcardan** [comment]
EvilDICOM does not support DICOMDir reading currently.
