### ISSUE TITLE
Allow reading from System.IO.Stream

### ISSUE THREAD

**Issue by feliwir** [rexcardan/Evil-DICOM#61]
Hello,

the `DICOMObject.Read` function only accepts a string to a file or a byte array. For convenience & performance reasons it would be nice if it also accepted a plain `Stream` objects, which covers both of these cases and allows for more advanced scenarios. I'd do a PR for that if this gets accepted.

**Comment by feliwir** [comment]
@crcrewso yes

**Comment by rexcardan** [comment]
I have thought about doing something like this with the new Span<T> once I migrate to .NET core. I would merge the PR if it is readable and the method is clean.

**Comment by feliwir** [comment]
@rexcardan there used to be already a PR for converting to .NET Standard. Any ETA when that can get merged?

**Comment by rexcardan** [comment]
It is on .NET Core 3 now.
