### ISSUE TITLE
Exception "Explicit VR syntax used but VR string is missing"

### ISSUE THREAD

**Issue by DominaTang** [rexcardan/Evil-DICOM#66]
"Explicit VR syntax used but VR string is missing" exception is thrown when opening some DICOM file, while I use fo-dicom NuGet package

**Comment by rexcardan** [comment]
Are you saying fo-dicom opens okay but Evil-DICOM does not?

**Comment by DominaTang** [comment]
Yes.

**Comment by rexcardan** [comment]
Do you have a sample file without patient information?

**Comment by rexcardan** [comment]
I think this is fixed per Recomia issue 71
