### ISSUE TITLE
Searching by tag takes too much time!

### ISSUE THREAD

**Issue by crcrewso** [rexcardan/Evil-DICOM#68]
The CompleteID property in EvilDICOM/EvilDICOM/Core/Element/Tag.cs takes more than 50% of the time of a FindEach or FindFirst call. This is due to how slow String.Concat is. There are other ways to speed up this search:

- Create a local variable for CompleteID and manage the getters and setters appropriately
- Create a local string[] to store Group and Element, Allowing `String.Join("", string[])` to work quickly 
- Other strategies that the author may have thought of that I have not. 

I discovered this while trying to improve the performance of EvilDICOM.RT.DoseMatrix.GetPointDose(). 

In migrating from your DoseMatrix to an immutable object I was able to get a 4000x improvement, half of which was just avoiding the findfirst() calls.

**Comment by rexcardan** [comment]
That's awesome. Why don't you submit a pull request with your improvements?

**Comment by rexcardan** [comment]
I just committed a fix for the Tag object not concatenating strings for each operation. Thanks for the tip. Would love to see your DoseMatrix implementation

**Comment by crcrewso** [comment]
I didn't submit my own PR because I saw 3 different directions and I wasn't sure which one would be better for the project as a whole. In the future I might be braver about that. 

My implementation can be found [here](DicomStrictCompare/DicomStrictCompare/Model/DoseMatrixOptimal.cs). It's inside a dose volume comparison tool for the specific use case of Version upgrades within the same Planning software. I hope to make this more general in the future.
