### ISSUE TITLE
Why finder.FindSeries does not return series' date?

### ISSUE THREAD

**Issue by jazb83** [rexcardan/Evil-DICOM#69]
I am working with series modality: "RTIMAGE".

For a single patient, I have a couple of "RTIMAGE" series. I want to pull them by "Acquisition Date" or "Series Date" but unfortunately "series = finder.FindSeries(study)" the serieDate attribute is always empty for all series (ie., CT, RTIMAGE, etc.)  ("Acquisition Date" is not supported in the CFindSeriesIOD yet) .

So, I am forced to go to the Image Level to retrieve the imageDate and to pull my series by date (using the ImageDate to figure it out the series).

![image](https://user-images.githubusercontent.com/36144065/63888417-bb399780-c993-11e9-9c64-21f620813e3e.png)

Why is it happening? I read the Varian System Server_v15.5_Dicom_Conformance Statement and the Attribute should be supported (I hope that I am not wrong).

**Comment by rexcardan** [comment]
Patched in 2.0.5.2 per your pull request. Thanks for contributing!
